# Section A: Data Structures & Control Structures    
1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.


In [1]:
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original list:", numbers)

# 1. Append - add an element at the end
numbers.append(60)
print("After append(60):", numbers)

# 2. Extend - add multiple elements at the end
numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

# 3. Insert - add an element at a specific index
numbers.insert(2, 25)  # insert 25 at index 2
print("After insert(2, 25):", numbers)

# 4. Remove - remove first occurrence of a value
numbers.remove(40)
print("After remove(40):", numbers)

# 5. Pop - remove element at a specific index (default last)
popped = numbers.pop()  # removes last element
print("After pop():", numbers, "Popped element:", popped)

# 6. Index - find index of a value
index_30 = numbers.index(30)
print("Index of 30:", index_30)

# 7. Count - count occurrences of a value
count_20 = numbers.count(20)
print("Count of 20:", count_20)

# 8. Sort - sort the list in ascending order
numbers.sort()
print("After sort():", numbers)

# 9. Reverse - reverse the list
numbers.reverse()
print("After reverse():", numbers)

# 10. Clear - remove all elements
numbers.clear()
print("After clear():", numbers)


Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]
After pop(): [10, 20, 25, 30, 50, 60, 70] Popped element: 80
Index of 30: 3
Count of 20: 1
After sort(): [10, 20, 25, 30, 50, 60, 70]
After reverse(): [70, 60, 50, 30, 25, 20, 10]
After clear(): []


2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [3]:
# Create a tuple with 3 student names
students = ("Alice", "Bob", "Charlie")
print("Original tuple:", students)

# Try to change the second name
#students[1] = "David"


Original tuple: ('Alice', 'Bob', 'Charlie')


ans : if we change the second name in tuple it will give an error bcz A tuple in Python is immutable, which means its elements cannot be changed once the tuple is created,You cannot modify, add, or remove elements in a tuple.

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [4]:
# Create a set with some duplicate integers
numbers = {10, 20, 30, 20, 40, 10}
print("Set:", numbers)


Set: {40, 10, 20, 30}


ans : A set in Python is an unordered collection of unique elements,
Duplicates are automatically removed, so even though we added 20 and 10 twice, they appear only once in the set.

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [5]:
# Create a dictionary
student = {
    "name": "Alice",
    "age": 20,
    "city": "Mumbai"
}
print("Original dictionary:", student)

# Update the age
student["age"] = 21

# Add a new key 'email'
student["email"] = "alice@example.com"

# Print the final dictionary
print("Updated dictionary:", student)


Original dictionary: {'name': 'Alice', 'age': 20, 'city': 'Mumbai'}
Updated dictionary: {'name': 'Alice', 'age': 21, 'city': 'Mumbai', 'email': 'alice@example.com'}


5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [7]:
# Age of the person
age = 20

# Check voting eligibility
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote yet.")


You are eligible to vote.


6.	Given a 'marks' variable, print the grade:  
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [8]:
# Marks of the student
marks = 82

# Determine grade
if marks >= 90:
    grade = 'A'
elif marks >= 75:
    grade = 'B'
elif marks >= 50:
    grade = 'C'
else:
    grade = 'Fail'

print(f"Marks: {marks}, Grade: {grade}")


Marks: 82, Grade: B


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [11]:
# Number to check
num = 12

if num > 0:
    print("The number is positive.")
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("It is odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")


The number is positive.
It is also even.


# Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [15]:
import numpy as np

# 1. Scalar
scalar = np.array(5)
print("Scalar:", scalar)

# 2. 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", array_1d)

# 3. 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print("2D array:\n", array_2d)


Scalar: 5
1D array: [1 2 3 4 5]
2D array:
 [[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [16]:
import numpy as np

# Generate 4x4 array with random integers from 0 to 100
random_array = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random Array:\n", random_array)


4x4 Random Array:
 [[95  3 35 95]
 [66 86 17  1]
 [35 45 27  5]
 [96 51 39 38]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [17]:
import numpy as np
import pandas as pd

# 1. Create a 2D NumPy array of shape (3x3)
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])
print("NumPy Array:\n", array_2d)

# 2. Convert it into a pandas DataFrame
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])
print("\nPandas DataFrame:\n", df)


NumPy Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Pandas DataFrame:
     A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


# Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows



In [18]:
import pandas as pd
import numpy as np

# 1. Create a small DataFrame manually with 10 rows
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'Age': [25, 30, 35, 40, 28, 33, 29, 31, 27, 30],
    'City': ['Mumbai', 'Delhi', 'Kolkata', 'Mumbai', 'Delhi', 'Chennai', 'Kolkata', 'Mumbai', 'Delhi', 'Chennai'],
    'Salary': [50000, 60000, 70000, np.nan, 55000, 65000, 60000, np.nan, 58000, 62000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# 2. Use .info() and .describe()
print("\nDataFrame info:")
print(df.info())

print("\nDataFrame description:")
print(df.describe())

# 3. Select 'Name' and 'City' columns
name_city = df[['Name', 'City']]
print("\nSelected columns (Name and City):\n", name_city)

# 4. Drop 'City' column
df_dropped = df.drop('City', axis=1)
print("\nDataFrame after dropping 'City' column:\n", df_dropped)

# 5. Fill missing values in 'Salary' column with mean
salary_mean = df['Salary'].mean()
df['Salary'].fillna(salary_mean, inplace=True)
print("\nDataFrame after filling missing Salary values:\n", df)

# 6. Remove any duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\nDataFrame after removing duplicates:\n", df_no_duplicates)


Original DataFrame:
       Name  Age     City   Salary
0    Alice   25   Mumbai  50000.0
1      Bob   30    Delhi  60000.0
2  Charlie   35  Kolkata  70000.0
3    David   40   Mumbai      NaN
4      Eva   28    Delhi  55000.0
5    Frank   33  Chennai  65000.0
6    Grace   29  Kolkata  60000.0
7   Hannah   31   Mumbai      NaN
8      Ian   27    Delhi  58000.0
9     Jack   30  Chennai  62000.0

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

DataFrame description:
             Age        Salary
count  10.000000      8.000000
mean   30.800000  60000.000000
std     4.315347   6071.008389
min    25.000000  50000.000000
25%    28.2500

/tmp/ipython-input-884587089.py:32: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(salary_mean, inplace=True)
